#!/bin/bash
set -e

if [ -z "$1" ]; then
  echo "Usage: $0 <iterations> [branch-name]"
  echo "Example: $0 5 ralf/add-user-auth"
  exit 1
fi

# Create a new branch for ralf's work
if [ -n "$2" ]; then
  BRANCH="$2"
else
  # Generate random name from dictionary (4-8 char lowercase words)
  get_word() {
    grep -E '^[a-z]{4,8}$' /usr/share/dict/words | shuf -n 1
  }
  BRANCH="ralf/$(get_word)-$(get_word)-$(get_word)"
fi
BASE_BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo "Creating branch: $BRANCH (from $BASE_BRANCH)"
git checkout -b "$BRANCH"

for ((i=1; i<=$1; i++)); do
  echo "=== Iteration $i of $1 ==="

  result=$(claude --permission-mode acceptEdits -p "/frontend-designer /frontend-engineer @SPEC.md @progress.txt \\
  1. Find the highest-priority task and implement it. \\
  2. Run your tests and type checks. \\
  3. Update the SPEC with what was done. \\
  4. Append your progress to progress.txt. \\
  5. Commit your changes. \\
  ONLY WORK ON A SINGLE TASK. \\
  If the SPEC is complete, output <promise>COMPLETE</promise>.")

  echo "$result"

  if [[ "$result" == *"<promise>COMPLETE</promise>"* ]]; then
    echo "SPEC complete after $i iterations."
    break
  fi
done

# Push and create PR
echo "Pushing branch and creating PR..."
git push -u origin "$BRANCH"

gh pr create \
  --title "Ralf: Automated implementation from SPEC" \
  --body "This PR was automatically generated by ralf.sh.

## Summary
Completed $i iteration(s) implementing tasks from SPEC.md.

## Review
Please review the changes and the updated SPEC.md to verify all tasks were completed correctly." \
  --base "$BASE_BRANCH"

echo "Done! PR created for review."
