#!/bin/bash
set -e

# Parse named flags
while getopts "n:f:" opt; do
  case $opt in
    n) ITERATIONS="$OPTARG" ;;
    f) SPEC_FILE="$OPTARG" ;;
    \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
  esac
done

# Defaults
ITERATIONS="${ITERATIONS:-20}"
SPEC_FILE="${SPEC_FILE:-SPEC.md}"

# Validate dependencies
require_command() {
  for cmd in "$@"; do
    if ! command -v "$cmd" &>/dev/null; then
      echo "Error: Required command '$cmd' not found"
      exit 1
    fi
  done
}

require_command jq gh claude

# Validate files
if [[ ! -f "$SPEC_FILE" ]]; then
  echo "Error: $SPEC_FILE not found"
  exit 1
fi

[[ -f progress.txt ]] || touch progress.txt

# Get current branch name
BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Iteration loop
for ((i=1; i<=ITERATIONS; i++)); do
  echo "=== Iteration $i ==="

  result=$(claude --permission-mode acceptEdits -p "@$SPEC_FILE @progress.txt
1. Find the highest-priority task and implement it.
2. Run your tests and type checks.
3. Update the SPEC with what was done.
4. Append your progress to progress.txt.
5. Commit your changes with format: ralf: lowercase description
ONLY WORK ON A SINGLE TASK.
If the SPEC is complete, output <promise>COMPLETE</promise>.")

  echo "$result"

  if [[ "$result" == *"<promise>COMPLETE</promise>"* ]]; then
    echo "SPEC complete!"
    break
  fi
done

# Push and create PR
echo "Pushing branch..."
git push -u origin "$BRANCH"

# Detect default branch for diff/PR base
DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d: -f2 | tr -d ' ')

# Generate PR title and description
echo "Generating PR description..."
DIFF=$(git diff "$DEFAULT_BRANCH"...HEAD --stat)

# Check if PR exists
EXISTING_PR=""
if gh pr view --json title,body -q '.' &>/dev/null; then
  EXISTING_TITLE=$(gh pr view --json title -q '.title')
  EXISTING_BODY=$(gh pr view --json body -q '.body')
  EXISTING_PR="Current PR title: $EXISTING_TITLE

Current PR description:
$EXISTING_BODY

Update the title and description to reflect all changes, or keep if still accurate."
fi

pr_json=$(claude -p "You are writing a PR title and description.

@$SPEC_FILE
@progress.txt

Here is the diff summary:
$DIFF

$EXISTING_PR

Output ONLY valid JSON with this structure, no other text:
{\"title\": \"Short descriptive title\", \"description\": \"## Summary\\n\\nBullet points of changes...\"}")

# Parse JSON (fallback to defaults if parsing fails)
PR_TITLE=$(echo "$pr_json" | jq -r '.title' 2>/dev/null) || PR_TITLE="Ralf: Implementation from SPEC"
PR_BODY=$(echo "$pr_json" | jq -r '.description' 2>/dev/null) || PR_BODY="Automated implementation from SPEC.md"

# Add footer to PR body
PR_BODY="$PR_BODY

---
*Generated by ralf.sh*"

# Create or update PR
if [ -n "$EXISTING_PR" ]; then
  echo "Updating existing PR..."
  gh pr edit --title "$PR_TITLE" --body "$PR_BODY"
else
  echo "Creating new PR..."
  gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base "$DEFAULT_BRANCH"
fi

echo "Done!"
